In [3]:
import numpy as np

def solve(grid, r=0, c=0):
    if r == 9:
        return True
    if grid[r][c] != 0:
        return solve(grid, r + (c + 1) // 9, (c + 1) % 9)

    for k in range(1, 10):
        if is_valid(grid, r, c, k):
            grid[r][c] = k
            if solve(grid, r + (c + 1) // 9, (c + 1) % 9):
                return True
    grid[r][c] = 0
    return False

def is_valid(grid, r, c, k):
    return not any(grid[r][j] == k for j in range(9)) \
        and not any(grid[i][c] == k for i in range(9)) \
        and not any(grid[r // 3 * 3 + i][c // 3 * 3 + j] == k
                    for i in range(3) for j in range(3))

# Define puzzle using numpy array
puzzle = np.array([
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
])

if solve(puzzle):
    print("Solved Sudoku:")
    print(puzzle)
else:
    print("No solution exists.")


Solved Sudoku:
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
